### ISSUE TITLE
问题 提交

### ISSUE THREAD

**Issue by sugyli** [medz/zank-web#1]
问题 1
根目录 zank文件 require __DIR__.'/src/db/console.php';
console.php'  第13行  
$capsule->setAsGlobal();  这个方法应该是  // 设置全局静态可访问
 这个方法好像不存在;

我在 THINKSNS的 文件扩展中 发现这个方法存在
	public function setAsGlobal()
	{
		static::$instance = $this;
	}

可能上面的问题导致 下面的问题
在SRC/TableImportCommand.php 类中

大约在38行
foreach ($finder as $file) {
            $tableName = $file->getBasename('.php');
            Capsule::Schema()->dropIfExists($tableName); // 删除数据库的表
            $handle = require $tablesDir.'/'.$tableName.'.php';
            Capsule::Schema()->create($tableName, $handle);
            $output->writeln('Create table:'.$tableName.' <fg=green>OK.</>');
            $i++;
        }
  Capsule::Schema()->dropIfExists($tableName); // 删除数据库的表
第一件事情是删除数据中的表  但是如果我是第一用  也就是说我连库都没有 这个地方会报错

**Comment by medz** [comment]
这个周末说呢～库问题并不归程序管
