### ISSUE TITLE
提交个BUG

### ISSUE THREAD

**Issue by sugyli** [medz/zank-web#42]
Zank\Middleware\Captcha\ValidateByPhoneCaptcha

        // 验证手机号码是否为空
        if (!$phone) {
            $response = new \Zank\Common\Message($response, false, '手机号码不能为空');

            return $response->withJson();

        // 验证验证码是否为空
        } elseif (!$phoneCaptcha) {
            $response = new \Zank\Common\Message($response, false, '验证码不能为空');

            return $response->withJson();
        }

不能用ELSEIF   不然其中一个为空了  会继续向下走  要分开验证

**Comment by medz** [comment]
逻辑没问题呀～如果是手机号码为空，第一个if就return了～如果是验证码为空，到了elseif就return了，走不到查询数据库的步骤～
